= The projects on github/christianpopescu
Doc Writer <christian.popescu@outlook.com>
v 1.1, 2023-01-19
:sectnums:
:toc:
:toclevels: 5

== The projects


=== SDEToolsPoc

https://github.com/christianpopescu/SDEToolsPoc

* File Helper
It is a helper to change file content based on regular expressions

SDEToolsPoc/src/NetCore/SDETools/src/FileHelper/

* Collections abstract data type

    SDEToolsPoc/src/NetCore/SDETools/src/AbstractDataHelper/Collections/

    ListOfElements to develop further

=== Poc

https://github.com/christianpopescu/Poc

Main Poc for different projects and technologies

=== LaSdeCppTool

Light Agile Software Development Engineer Tool

https://github.com/christianpopescu/LaSdeCppTool

This is the C++ version

https://github.com/christianpopescu/LaSdeCppTool/blob/main/doc/LaSdeCppTool.adoc

=== PySDETools

https://github.com/christianpopescu/PySDETools

=== WinClientToLinux

https://github.com/christianpopescu/WinClientToLinux

SFTP, SSH, etc. client from Windows to Linux

Uses Renci.

=== DevOpsHelperTools

https://github.com/christianpopescu/DevOpsHelperTools

Admin scripts for Oracle

Scripts for Version Control SVN (dump repository, load, etc).

=== SDEToolsServer

https://github.com/christianpopescu/SDEToolsServer

* Developped in C#

* Small Socket server