= The projects on github/christianpopescu
Doc Writer <christian.popescu@outlook.com>
v 1.3, 2023-11-10
:sectnums:
:toc:
:toclevels: 5
:pdf-page-size:A3

== The projects



=== Knowledge Management

https://github.com/christianpopescu/KnowledgeManagement

The purpose is to keep in one place some useful information that I've gathered during my professional activity.


=== KMCpp

*Knowledge Management for C++*

It contains:

* Useful links for resources, blogs, etc.
* Articles on different subjects.

=== KmSoftwareDevelopment

https://github.com/christianpopescu/KmSoftwareDevelopment/


The purpose is to document some standard task used during development implemented in different languages.

=== SDEToolsPoc

https://github.com/christianpopescu/SDEToolsPoc

* File Helper
It is a helper to change file content based on regular expressions

SDEToolsPoc/src/NetCore/SDETools/src/FileHelper/

* Collections abstract data type

    SDEToolsPoc/src/NetCore/SDETools/src/AbstractDataHelper/Collections/

    ListOfElements to develop further

=== Poc

https://github.com/christianpopescu/Poc

Main Poc for different projects and technologies

=== LaSdeCppTool

Light Agile Software Development Engineer Tool Developed in C++

https://github.com/christianpopescu/LaSdeCppTool

This is the C++ version

https://github.com/christianpopescu/LaSdeCppTool/blob/main/doc/LaSdeCppTool.adoc

=== PySDETools

https://github.com/christianpopescu/PySDETools

=== WinClientToLinux

https://github.com/christianpopescu/WinClientToLinux

SFTP, SSH, etc. client from Windows to Linux

Uses Renci.

=== DevOpsHelperTools

https://github.com/christianpopescu/DevOpsHelperTools

Admin scripts for Oracle

Scripts for Version Control SVN (dump repository, load, etc).

=== SDEToolsServer

https://github.com/christianpopescu/SDEToolsServer

* Developped in C#

* Small Socket server

=== SDEHelpers

https://github.com/christianpopescu/SDEHelpers

Script to add on development: scripts, project patterns, make files

=== NetFrameworkCSharp

!!!! To document